
local DesignResConfig = {}

DesignResConfig.Coordinates = {
    [1] = {
        Index = 1,
        Position = Vector3.new(419.45, -0.2, -164.49),
        PosId = 1,
        MapId = 101,
        Resource = 1,
        Refresh = 1,
        Probability = 0,
        DropGroup = 1,
        CanisterId = 501,
    },
    [2] = {
        Index = 2,
        Position = Vector3.new(444.98, -0.2, -149.37),
        PosId = 2,
        MapId = 101,
        Resource = 1,
        Refresh = 1,
        Probability = 0,
        DropGroup = 2,
        CanisterId = 501,
    },
    [3] = {
        Index = 3,
        Position = Vector3.new(435.36, -0.2, -209.58),
        PosId = 3,
        MapId = 101,
        Resource = 1,
        Refresh = 1,
        Probability = 0,
        DropGroup = 1,
        CanisterId = 501,
    },
    [4] = {
        Index = 4,
        Position = Vector3.new(475.77, -0.2, -199.06),
        PosId = 4,
        MapId = 101,
        Resource = 1,
        Refresh = 2,
        Probability = 1000,
        DropGroup = 2,
        CanisterId = 501,
    },
    [5] = {
        Index = 5,
        Position = Vector3.new(472.86, -0.2, -177.05),
        PosId = 5,
        MapId = 101,
        Resource = 1,
        Refresh = 2,
        Probability = 2000,
        DropGroup = 1,
        CanisterId = 501,
    },
    [6] = {
        Index = 6,
        Position = Vector3.new(489.52, -0.2, -156.4),
        PosId = 6,
        MapId = 101,
        Resource = 2,
        Refresh = 1,
        Probability = 0,
        DropGroup = 2,
        CanisterId = 501,
    },
    [7] = {
        Index = 7,
        Position = Vector3.new(468.24, -0.2, -83.71),
        PosId = 7,
        MapId = 101,
        Resource = 2,
        Refresh = 1,
        Probability = 0,
        DropGroup = 1,
        CanisterId = 501,
    },
    [8] = {
        Index = 8,
        Position = Vector3.new(622.76, 0.8, -65.42),
        PosId = 8,
        MapId = 101,
        Resource = 2,
        Refresh = 2,
        Probability = 1000,
        DropGroup = 2,
        CanisterId = 501,
    },
    [9] = {
        Index = 9,
        Position = Vector3.new(565.4, 0.8, 30.07),
        PosId = 9,
        MapId = 101,
        Resource = 2,
        Refresh = 2,
        Probability = 2000,
        DropGroup = 1,
        CanisterId = 501,
    },
    [10] = {
        Index = 10,
        Position = Vector3.new(434.64, 15.4, -33.54),
        PosId = 10,
        MapId = 101,
        Resource = 2,
        Refresh = 2,
        Probability = 3000,
        DropGroup = 2,
        CanisterId = 501,
    },
    [11] = {
        Index = 11,
        Position = Vector3.new(306.17, -0.2, -199.19),
        PosId = 11,
        MapId = 101,
        Resource = 3,
        Refresh = 1,
        Probability = 0,
        DropGroup = 1,
        CanisterId = 501,
    },
    [12] = {
        Index = 12,
        Position = Vector3.new(293.92, -0.2, -165.1),
        PosId = 12,
        MapId = 101,
        Resource = 3,
        Refresh = 1,
        Probability = 0,
        DropGroup = 2,
        CanisterId = 501,
    },
    [13] = {
        Index = 13,
        Position = Vector3.new(238.6, -0.2, -167.65),
        PosId = 13,
        MapId = 101,
        Resource = 3,
        Refresh = 2,
        Probability = 1000,
        DropGroup = 1,
        CanisterId = 501,
    },
    [14] = {
        Index = 14,
        Position = Vector3.new(233.16, -0.2, -203.58),
        PosId = 14,
        MapId = 101,
        Resource = 4,
        Refresh = 1,
        Probability = 0,
        DropGroup = 2,
        CanisterId = 501,
    },
    [15] = {
        Index = 15,
        Position = Vector3.new(165.37, -0.2, -148.04),
        PosId = 15,
        MapId = 101,
        Resource = 4,
        Refresh = 1,
        Probability = 0,
        DropGroup = 1,
        CanisterId = 501,
    },
    [16] = {
        Index = 16,
        Position = Vector3.new(166.34, -0.2, -85.88),
        PosId = 16,
        MapId = 101,
        Resource = 4,
        Refresh = 2,
        Probability = 1000,
        DropGroup = 2,
        CanisterId = 501,
    },
    [17] = {
        Index = 17,
        Position = Vector3.new(106.25, 55.2, -112.9),
        PosId = 17,
        MapId = 101,
        Resource = 4,
        Refresh = 2,
        Probability = 2000,
        DropGroup = 1,
        CanisterId = 501,
    },
    [18] = {
        Index = 18,
        Position = Vector3.new(201.38, 84.01, -89.09),
        PosId = 18,
        MapId = 101,
        Resource = 5,
        Refresh = 3,
        Probability = 2001,
        DropGroup = 2,
        CanisterId = 501,
    },
    [19] = {
        Index = 19,
        Position = Vector3.new(-154.48, -0.2, -35.21),
        PosId = 19,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [20] = {
        Index = 20,
        Position = Vector3.new(-233.91, -0.2, -99.74),
        PosId = 20,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [21] = {
        Index = 21,
        Position = Vector3.new(36.77, -0.2, -110.91),
        PosId = 21,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [22] = {
        Index = 22,
        Position = Vector3.new(-143.44, 35.6, -28.44),
        PosId = 22,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [23] = {
        Index = 23,
        Position = Vector3.new(-162.32, 86.58, 47.17),
        PosId = 23,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [24] = {
        Index = 24,
        Position = Vector3.new(-318.47, 0.8, -159.3),
        PosId = 24,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [25] = {
        Index = 25,
        Position = Vector3.new(-70.92, -0.19, 97.94),
        PosId = 25,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [26] = {
        Index = 26,
        Position = Vector3.new(-725.8, 26.4, 362.3),
        PosId = 26,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [27] = {
        Index = 27,
        Position = Vector3.new(-774.7, 0.8, 343.1),
        PosId = 27,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [28] = {
        Index = 28,
        Position = Vector3.new(-889.9, -0.2, 812.9),
        PosId = 28,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [29] = {
        Index = 29,
        Position = Vector3.new(-928.5, -0.2, 819.4),
        PosId = 29,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [30] = {
        Index = 30,
        Position = Vector3.new(-1028.3, -1.2, 955.2),
        PosId = 30,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [31] = {
        Index = 31,
        Position = Vector3.new(-1002.3, -0.2, 1001.2),
        PosId = 31,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [32] = {
        Index = 32,
        Position = Vector3.new(-1010.8, 13, 1016.5),
        PosId = 32,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [33] = {
        Index = 33,
        Position = Vector3.new(-941.4, -0.2, 1037.7),
        PosId = 33,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [34] = {
        Index = 34,
        Position = Vector3.new(-890.3, -0.2, 976.3),
        PosId = 34,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [35] = {
        Index = 35,
        Position = Vector3.new(-873.2, -0.2, 961.2),
        PosId = 35,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [36] = {
        Index = 36,
        Position = Vector3.new(-873.4, -0.2, 949.9),
        PosId = 36,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [37] = {
        Index = 37,
        Position = Vector3.new(-892.9, -0.2, 952.3),
        PosId = 37,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [38] = {
        Index = 38,
        Position = Vector3.new(-882.1, -0.2, 1011.6),
        PosId = 38,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [39] = {
        Index = 39,
        Position = Vector3.new(-935.4, 11.9, 1024.7),
        PosId = 39,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [40] = {
        Index = 40,
        Position = Vector3.new(-928.9, -0.2, 1020.6),
        PosId = 40,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [41] = {
        Index = 41,
        Position = Vector3.new(-909.9, -0.2, 1022.4),
        PosId = 41,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [42] = {
        Index = 42,
        Position = Vector3.new(-799.4, -0.2, 994.2),
        PosId = 42,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [43] = {
        Index = 43,
        Position = Vector3.new(758.8, -0.2, 543.1),
        PosId = 43,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [44] = {
        Index = 44,
        Position = Vector3.new(837.1, 1.9, 815.5),
        PosId = 44,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [45] = {
        Index = 45,
        Position = Vector3.new(827.2, -0.2, 577.7),
        PosId = 45,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [46] = {
        Index = 46,
        Position = Vector3.new(885.3, 24.8, 414.3),
        PosId = 46,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [47] = {
        Index = 47,
        Position = Vector3.new(954.4, 44.2, 608.7),
        PosId = 47,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [48] = {
        Index = 48,
        Position = Vector3.new(918.2, 44.2, 576.9),
        PosId = 48,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [49] = {
        Index = 49,
        Position = Vector3.new(986.9, 84.2, 561.5),
        PosId = 49,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [50] = {
        Index = 50,
        Position = Vector3.new(400.22, -0.2, -0.37),
        PosId = 50,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [51] = {
        Index = 51,
        Position = Vector3.new(422.44, -0.2, -51.09),
        PosId = 51,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [52] = {
        Index = 52,
        Position = Vector3.new(203.31, -0.2, -173.49),
        PosId = 52,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [53] = {
        Index = 53,
        Position = Vector3.new(212.99, -0.2, -86.23),
        PosId = 53,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [54] = {
        Index = 54,
        Position = Vector3.new(138.28, -0.2, -135.94),
        PosId = 54,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [55] = {
        Index = 55,
        Position = Vector3.new(129.23, -0.2, 63.19),
        PosId = 55,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [56] = {
        Index = 56,
        Position = Vector3.new(91.73, 46.01, -100.4),
        PosId = 56,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [57] = {
        Index = 57,
        Position = Vector3.new(211.6, 77.8, -106.7),
        PosId = 57,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [58] = {
        Index = 58,
        Position = Vector3.new(54.41, -1.2, -9.29),
        PosId = 58,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [59] = {
        Index = 59,
        Position = Vector3.new(43.98, -0.2, 79.94),
        PosId = 59,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [60] = {
        Index = 60,
        Position = Vector3.new(-13.55, -0.2, 6.94),
        PosId = 60,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [61] = {
        Index = 61,
        Position = Vector3.new(-159.2, 35.6, -50.53),
        PosId = 61,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [62] = {
        Index = 62,
        Position = Vector3.new(-147.43, 67, -4.77),
        PosId = 62,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [63] = {
        Index = 63,
        Position = Vector3.new(-150.62, 36.6, -61.04),
        PosId = 63,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [64] = {
        Index = 64,
        Position = Vector3.new(-171.97, -0.2, -45.22),
        PosId = 64,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [65] = {
        Index = 65,
        Position = Vector3.new(34.02, -0.19, 64.04),
        PosId = 65,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [66] = {
        Index = 66,
        Position = Vector3.new(-550.7, 75.4, 305.6),
        PosId = 66,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [67] = {
        Index = 67,
        Position = Vector3.new(-659.9, 26.4, 317),
        PosId = 67,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [68] = {
        Index = 68,
        Position = Vector3.new(-728.8, 10, 477.2),
        PosId = 68,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [69] = {
        Index = 69,
        Position = Vector3.new(-820.9, 10, 480.3),
        PosId = 69,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [70] = {
        Index = 70,
        Position = Vector3.new(-854.4, -0.2, 950.3),
        PosId = 70,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [71] = {
        Index = 71,
        Position = Vector3.new(-742.8, -0.2, 946.9),
        PosId = 71,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [72] = {
        Index = 72,
        Position = Vector3.new(738.9, 10.4, 505.7),
        PosId = 72,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [73] = {
        Index = 73,
        Position = Vector3.new(723.6, -0.2, 573.4),
        PosId = 73,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [74] = {
        Index = 74,
        Position = Vector3.new(718.4, -0.2, 721.1),
        PosId = 74,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [75] = {
        Index = 75,
        Position = Vector3.new(670, -0.2, 878.5),
        PosId = 75,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [76] = {
        Index = 76,
        Position = Vector3.new(747.8, -0.2, 799.4),
        PosId = 76,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [77] = {
        Index = 77,
        Position = Vector3.new(795.2, -0.2, 761.9),
        PosId = 77,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [78] = {
        Index = 78,
        Position = Vector3.new(877.1, -1.2, 715),
        PosId = 78,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [79] = {
        Index = 79,
        Position = Vector3.new(890.2, -0.2, 594.9),
        PosId = 79,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [80] = {
        Index = 80,
        Position = Vector3.new(963.2, -0.2, 556.2),
        PosId = 80,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [81] = {
        Index = 81,
        Position = Vector3.new(1042.8, -0.2, 538.7),
        PosId = 81,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [82] = {
        Index = 82,
        Position = Vector3.new(941.1, -0.2, 700.3),
        PosId = 82,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [83] = {
        Index = 83,
        Position = Vector3.new(894.3, 44.8, 653),
        PosId = 83,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [84] = {
        Index = 84,
        Position = Vector3.new(892.9, 66.9, 603.5),
        PosId = 84,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [85] = {
        Index = 85,
        Position = Vector3.new(789.7, 79.4, 719.5),
        PosId = 85,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [86] = {
        Index = 86,
        Position = Vector3.new(799.1, 89.1, 659.1),
        PosId = 86,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [87] = {
        Index = 87,
        Position = Vector3.new(365.95, -1.2, -217.86),
        PosId = 87,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [88] = {
        Index = 88,
        Position = Vector3.new(428.39, -0.2, -82.61),
        PosId = 88,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [89] = {
        Index = 89,
        Position = Vector3.new(179.4, -0.2, -201.62),
        PosId = 89,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [90] = {
        Index = 90,
        Position = Vector3.new(237.27, -0.2, 2.42),
        PosId = 90,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [91] = {
        Index = 91,
        Position = Vector3.new(107.4, 22.4, 80.62),
        PosId = 91,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [92] = {
        Index = 92,
        Position = Vector3.new(58.82, 36.61, -116.02),
        PosId = 92,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [93] = {
        Index = 93,
        Position = Vector3.new(144.54, 73.4, -162.02),
        PosId = 93,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [94] = {
        Index = 94,
        Position = Vector3.new(-70.91, 58.81, -14.1),
        PosId = 94,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [95] = {
        Index = 95,
        Position = Vector3.new(-173.48, 80.6, -7.74),
        PosId = 95,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [96] = {
        Index = 96,
        Position = Vector3.new(-159.18, 36.6, -97),
        PosId = 96,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [97] = {
        Index = 97,
        Position = Vector3.new(-306.92, -0.2, -96.06),
        PosId = 97,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 0,
        DropGroup = nil,
        CanisterId = 0,
    },
    [98] = {
        Index = 98,
        Position = Vector3.new(-92.63, -0.2, 44.39),
        PosId = 98,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [99] = {
        Index = 99,
        Position = Vector3.new(-636.3, 45.2, 297.4),
        PosId = 99,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [100] = {
        Index = 100,
        Position = Vector3.new(-841, -0.2, 272.4),
        PosId = 100,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [101] = {
        Index = 101,
        Position = Vector3.new(-724.6, -0.2, 716.8),
        PosId = 101,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [102] = {
        Index = 102,
        Position = Vector3.new(-760.8, -0.2, 749.7),
        PosId = 102,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [103] = {
        Index = 103,
        Position = Vector3.new(-749.4, -0.2, 874.6),
        PosId = 103,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [104] = {
        Index = 104,
        Position = Vector3.new(-1033.5, -0.2, 878.6),
        PosId = 104,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [105] = {
        Index = 105,
        Position = Vector3.new(-960.1, -0.2, 1059.1),
        PosId = 105,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [106] = {
        Index = 106,
        Position = Vector3.new(-623.8, -0.2, 911),
        PosId = 106,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [107] = {
        Index = 107,
        Position = Vector3.new(-614.9, -0.2, 842.3),
        PosId = 107,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [108] = {
        Index = 108,
        Position = Vector3.new(-609.9, -0.2, 757.3),
        PosId = 108,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [109] = {
        Index = 109,
        Position = Vector3.new(674.3, -0.2, 478),
        PosId = 109,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [110] = {
        Index = 110,
        Position = Vector3.new(582.7, -0.2, 727.1),
        PosId = 110,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [111] = {
        Index = 111,
        Position = Vector3.new(863.8, -1.2, 729.9),
        PosId = 111,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 501,
    },
    [112] = {
        Index = 112,
        Position = Vector3.new(1005.8, -0.2, 517.7),
        PosId = 112,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [113] = {
        Index = 113,
        Position = Vector3.new(711.8, -0.2, 990.8),
        PosId = 113,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [114] = {
        Index = 114,
        Position = Vector3.new(582.8, -0.2, 887.6),
        PosId = 114,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [115] = {
        Index = 115,
        Position = Vector3.new(908.6, 84.2, 629.4),
        PosId = 115,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [116] = {
        Index = 116,
        Position = Vector3.new(863.6, 92.2, 808.7),
        PosId = 116,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [117] = {
        Index = 117,
        Position = Vector3.new(808.4, 109.4, 619.2),
        PosId = 117,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [118] = {
        Index = 118,
        Position = Vector3.new(244.04, -0.2, -47.81),
        PosId = 118,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [119] = {
        Index = 119,
        Position = Vector3.new(50.51, -0.2, 67.63),
        PosId = 119,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [120] = {
        Index = 120,
        Position = Vector3.new(51.36, -0.2, 59.01),
        PosId = 120,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [121] = {
        Index = 121,
        Position = Vector3.new(55.61, -0.2, 43.87),
        PosId = 121,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [122] = {
        Index = 122,
        Position = Vector3.new(-285.41, -0.2, -109.38),
        PosId = 122,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [123] = {
        Index = 123,
        Position = Vector3.new(-124.71, -0.2, 29.17),
        PosId = 123,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [124] = {
        Index = 124,
        Position = Vector3.new(-627.6, 45.2, 272.4),
        PosId = 124,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 5000,
        DropGroup = nil,
        CanisterId = 502,
    },
    [125] = {
        Index = 125,
        Position = Vector3.new(-753.5, 0.8, 398.5),
        PosId = 125,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 10000,
        DropGroup = nil,
        CanisterId = 503,
    },
    [126] = {
        Index = 126,
        Position = Vector3.new(-799.6, 0.8, 286.2),
        PosId = 126,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 10000,
        DropGroup = nil,
        CanisterId = 601,
    },
    [127] = {
        Index = 127,
        Position = Vector3.new(-598.3, -0.2, 918.3),
        PosId = 127,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 10000,
        DropGroup = nil,
        CanisterId = 601,
    },
    [128] = {
        Index = 128,
        Position = Vector3.new(1021.8, -0.2, 645.5),
        PosId = 128,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 10000,
        DropGroup = nil,
        CanisterId = 601,
    },
    [129] = {
        Index = 129,
        Position = Vector3.new(581.2, -0.2, 873),
        PosId = 129,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 10000,
        DropGroup = nil,
        CanisterId = 601,
    },
    [130] = {
        Index = 130,
        Position = Vector3.new(828.1, 92.2, 916.6),
        PosId = 130,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = 10000,
        DropGroup = nil,
        CanisterId = 601,
    },
    [131] = {
        Index = 131,
        Position = Vector3.new(0, 0, 0),
        PosId = nil,
        MapId = nil,
        Resource = nil,
        Refresh = nil,
        Probability = {
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    10000,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
        DropGroup = nil,
        CanisterId = {
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    601,
    603,
    701,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    },
}

-- 辅助函数
function DesignResConfig:GetByIndex(index)
    return self.Coordinates[index]
end

function DesignResConfig:GetByPosId(value)
    for i, item in pairs(self.Coordinates) do
        if item.PosId == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetByMapId(value)
    for i, item in pairs(self.Coordinates) do
        if item.MapId == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetByResource(value)
    for i, item in pairs(self.Coordinates) do
        if item.Resource == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetByRefresh(value)
    for i, item in pairs(self.Coordinates) do
        if item.Refresh == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetByProbability(value)
    for i, item in pairs(self.Coordinates) do
        if item.Probability == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetByDropGroup(value)
    for i, item in pairs(self.Coordinates) do
        if item.DropGroup == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetByCanisterId(value)
    for i, item in pairs(self.Coordinates) do
        if item.CanisterId == value then
            return item
        end
    end
    return nil
end

function DesignResConfig:GetAll()
    return self.Coordinates
end

function DesignResConfig:GetCount()
    local count = 0
    for _ in pairs(self.Coordinates) do
        count = count + 1
    end
    return count
end

return DesignResConfig