
local DesignMonsterConfig = {}

DesignMonsterConfig.Coordinates = {
    [1] = {
        Index = 1,
        Position = Vector3.new(446.89, -0.2, -65.11),
        PosId = 1,
        MapId = 101,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30001,
        MonsterName = nil,
    },
    [2] = {
        Index = 2,
        Position = Vector3.new(436.6, -0.2, -177.16),
        PosId = 2,
        MapId = 101,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30002,
        MonsterName = nil,
    },
    [3] = {
        Index = 3,
        Position = Vector3.new(372.25, -1.2, -6.56),
        PosId = 3,
        MapId = 101,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30003,
        MonsterName = nil,
    },
    [4] = {
        Index = 4,
        Position = Vector3.new(218.32, -0.2, -230.32),
        PosId = 4,
        MapId = 101,
        Refresh = 2,
        Probability = 1000,
        MonsterId = nil,
        MonsterName = nil,
    },
    [5] = {
        Index = 5,
        Position = Vector3.new(273.02, -0.2, -103.93),
        PosId = 5,
        MapId = 200,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30001,
        MonsterName = nil,
    },
    [6] = {
        Index = 6,
        Position = Vector3.new(166.15, -0.2, -119.15),
        PosId = 6,
        MapId = 200,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30002,
        MonsterName = nil,
    },
    [7] = {
        Index = 7,
        Position = Vector3.new(163.77, -0.2, 38.08),
        PosId = 7,
        MapId = 200,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30003,
        MonsterName = nil,
    },
    [8] = {
        Index = 8,
        Position = Vector3.new(201.96, -0.2, 26.54),
        PosId = 8,
        MapId = 200,
        Refresh = 2,
        Probability = 1000,
        MonsterId = nil,
        MonsterName = nil,
    },
    [9] = {
        Index = 9,
        Position = Vector3.new(12.75, 36.61, -25.51),
        PosId = 9,
        MapId = 300,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30001,
        MonsterName = nil,
    },
    [10] = {
        Index = 10,
        Position = Vector3.new(18.37, 36.61, -77.07),
        PosId = 10,
        MapId = 300,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30002,
        MonsterName = nil,
    },
    [11] = {
        Index = 11,
        Position = Vector3.new(96.55, 55.2, -118.41),
        PosId = 11,
        MapId = 300,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30003,
        MonsterName = nil,
    },
    [12] = {
        Index = 12,
        Position = Vector3.new(-41.47, 36.61, -15.37),
        PosId = 12,
        MapId = 300,
        Refresh = 2,
        Probability = 1000,
        MonsterId = nil,
        MonsterName = nil,
    },
    [13] = {
        Index = 13,
        Position = Vector3.new(-113.39, 58.8, -30.62),
        PosId = 13,
        MapId = 400,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30001,
        MonsterName = nil,
    },
    [14] = {
        Index = 14,
        Position = Vector3.new(-173.34, 86.58, 23.36),
        PosId = 14,
        MapId = 400,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30002,
        MonsterName = nil,
    },
    [15] = {
        Index = 15,
        Position = Vector3.new(-136.53, 36.6, -88.36),
        PosId = 15,
        MapId = 400,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30003,
        MonsterName = nil,
    },
    [16] = {
        Index = 16,
        Position = Vector3.new(-185.54, 36.6, -130.33),
        PosId = 16,
        MapId = 400,
        Refresh = 2,
        Probability = 1000,
        MonsterId = nil,
        MonsterName = nil,
    },
    [17] = {
        Index = 17,
        Position = Vector3.new(-232.69, 36.6, -76.87),
        PosId = 17,
        MapId = 500,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30001,
        MonsterName = nil,
    },
    [18] = {
        Index = 18,
        Position = Vector3.new(-287.71, -0.2, -129.38),
        PosId = 18,
        MapId = 500,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30002,
        MonsterName = nil,
    },
    [19] = {
        Index = 19,
        Position = Vector3.new(-62.53, -0.19, 67.16),
        PosId = 19,
        MapId = 500,
        Refresh = 1,
        Probability = 0,
        MonsterId = 30003,
        MonsterName = nil,
    },
    [20] = {
        Index = 20,
        Position = Vector3.new(21.21, -0.19, 101.65),
        PosId = 20,
        MapId = 500,
        Refresh = 2,
        Probability = 1000,
        MonsterId = nil,
        MonsterName = nil,
    },
    [21] = {
        Index = 21,
        Position = Vector3.new(-588.6, 61.8, 296),
        PosId = 21,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [22] = {
        Index = 22,
        Position = Vector3.new(-721.5, 26.4, 320.1),
        PosId = 22,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [23] = {
        Index = 23,
        Position = Vector3.new(-757.2, 26.4, 369.5),
        PosId = 23,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [24] = {
        Index = 24,
        Position = Vector3.new(-783.1, 26.4, 428.9),
        PosId = 24,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [25] = {
        Index = 25,
        Position = Vector3.new(-765.5, -0.2, 478.2),
        PosId = 25,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [26] = {
        Index = 26,
        Position = Vector3.new(-905.9, -0.2, 227.3),
        PosId = 26,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [27] = {
        Index = 27,
        Position = Vector3.new(-793, -0.2, 704.2),
        PosId = 27,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [28] = {
        Index = 28,
        Position = Vector3.new(-823.8, -0.2, 749.6),
        PosId = 28,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [29] = {
        Index = 29,
        Position = Vector3.new(-706.3, -1.2, 772.2),
        PosId = 29,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [30] = {
        Index = 30,
        Position = Vector3.new(-732.8, -1.2, 821.9),
        PosId = 30,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [31] = {
        Index = 31,
        Position = Vector3.new(688.2, -1.2, 879.5),
        PosId = 31,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [32] = {
        Index = 32,
        Position = Vector3.new(-806.6, -0.2, 822.5),
        PosId = 32,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [33] = {
        Index = 33,
        Position = Vector3.new(-1001.8, -1.2, 924.5),
        PosId = 33,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [34] = {
        Index = 34,
        Position = Vector3.new(-946.8, -0.2, 978.3),
        PosId = 34,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [35] = {
        Index = 35,
        Position = Vector3.new(-899.9, -0.2, 994.4),
        PosId = 35,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [36] = {
        Index = 36,
        Position = Vector3.new(-894.7, -0.2, 1056.2),
        PosId = 36,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [37] = {
        Index = 37,
        Position = Vector3.new(-832.5, -1.2, 892.8),
        PosId = 37,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [38] = {
        Index = 38,
        Position = Vector3.new(-694.5, -0.2, 928.2),
        PosId = 38,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [39] = {
        Index = 39,
        Position = Vector3.new(-634.9, -0.2, 928.2),
        PosId = 39,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [40] = {
        Index = 40,
        Position = Vector3.new(-566.8, -0.2, 926),
        PosId = 40,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [41] = {
        Index = 41,
        Position = Vector3.new(-528.3, -1.2, 860.6),
        PosId = 41,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [42] = {
        Index = 42,
        Position = Vector3.new(-577.5, -1.2, 841.9),
        PosId = 42,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [43] = {
        Index = 43,
        Position = Vector3.new(-561.8, -1.2, 795.3),
        PosId = 43,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [44] = {
        Index = 44,
        Position = Vector3.new(666.9, -0.2, 509.6),
        PosId = 44,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [45] = {
        Index = 45,
        Position = Vector3.new(690.8, -0.2, 551.8),
        PosId = 45,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [46] = {
        Index = 46,
        Position = Vector3.new(613, -0.2, 672.9),
        PosId = 46,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [47] = {
        Index = 47,
        Position = Vector3.new(603.5, -0.2, 816.1),
        PosId = 47,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [48] = {
        Index = 48,
        Position = Vector3.new(666.4, -0.2, 839.1),
        PosId = 48,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [49] = {
        Index = 49,
        Position = Vector3.new(721.5, -0.2, 851.5),
        PosId = 49,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [50] = {
        Index = 50,
        Position = Vector3.new(792, -0.2, 827.2),
        PosId = 50,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [51] = {
        Index = 51,
        Position = Vector3.new(830.1, -0.2, 733.1),
        PosId = 51,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [52] = {
        Index = 52,
        Position = Vector3.new(833.1, -0.2, 669.8),
        PosId = 52,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [53] = {
        Index = 53,
        Position = Vector3.new(1067.4, -0.2, 561.8),
        PosId = 53,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [54] = {
        Index = 54,
        Position = Vector3.new(1014.7, -0.2, 667.8),
        PosId = 54,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [55] = {
        Index = 55,
        Position = Vector3.new(967.5, -0.2, 758),
        PosId = 55,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [56] = {
        Index = 56,
        Position = Vector3.new(937.6, -0.2, 849.3),
        PosId = 56,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [57] = {
        Index = 57,
        Position = Vector3.new(744.6, -0.2, 976),
        PosId = 57,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [58] = {
        Index = 58,
        Position = Vector3.new(567.4, -0.2, 996.9),
        PosId = 58,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [59] = {
        Index = 59,
        Position = Vector3.new(607.4, -0.2, 897.1),
        PosId = 59,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [60] = {
        Index = 60,
        Position = Vector3.new(922.9, 84.2, 602.9),
        PosId = 60,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [61] = {
        Index = 61,
        Position = Vector3.new(883.9, 82.2, 690.7),
        PosId = 61,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [62] = {
        Index = 62,
        Position = Vector3.new(861.5, 82.2, 724.4),
        PosId = 62,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [63] = {
        Index = 63,
        Position = Vector3.new(876.1, 92.2, 780.3),
        PosId = 63,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [64] = {
        Index = 64,
        Position = Vector3.new(830.7, 92.2, 888.7),
        PosId = 64,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [65] = {
        Index = 65,
        Position = Vector3.new(813, 105.4, 641.8),
        PosId = 65,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
    [66] = {
        Index = 66,
        Position = Vector3.new(885.2, 24.8, 438.2),
        PosId = 66,
        MapId = nil,
        Refresh = nil,
        Probability = nil,
        MonsterId = nil,
        MonsterName = nil,
    },
}

-- 辅助函数
function DesignMonsterConfig:GetByIndex(index)
    return self.Coordinates[index]
end

function DesignMonsterConfig:GetByPosId(value)
    for i, item in pairs(self.Coordinates) do
        if item.PosId == value then
            return item
        end
    end
    return nil
end

function DesignMonsterConfig:GetByMapId(value)
    for i, item in pairs(self.Coordinates) do
        if item.MapId == value then
            return item
        end
    end
    return nil
end

function DesignMonsterConfig:GetByRefresh(value)
    for i, item in pairs(self.Coordinates) do
        if item.Refresh == value then
            return item
        end
    end
    return nil
end

function DesignMonsterConfig:GetByProbability(value)
    for i, item in pairs(self.Coordinates) do
        if item.Probability == value then
            return item
        end
    end
    return nil
end

function DesignMonsterConfig:GetByMonsterId(value)
    for i, item in pairs(self.Coordinates) do
        if item.MonsterId == value then
            return item
        end
    end
    return nil
end

function DesignMonsterConfig:GetByMonsterName(value)
    for i, item in pairs(self.Coordinates) do
        if item.MonsterName == value then
            return item
        end
    end
    return nil
end

function DesignMonsterConfig:GetAll()
    return self.Coordinates
end

function DesignMonsterConfig:GetCount()
    local count = 0
    for _ in pairs(self.Coordinates) do
        count = count + 1
    end
    return count
end

return DesignMonsterConfig