--[[
-- 自动生成的Lua配置文件
-- 生成时间: 2025-09-09 17:58:14
-- 源文件: examples\in\ItemConfig.xls
-- 数据维度: 79行 x 15列
--]]

-- Knit框架兼容的配置模块
local ItemConfig = {}

-- 配置数据
ItemConfig.Data = {
    [1] = {
        Index = 1,
        Item = "刺刀",
        DisplayName = "Bayonet",
        Icon = "rbxassetid://94897262399463",
        Model = "刺刀",
        Description = "A sharp close-combat weapon designed for piercing and slashing.",
        Type = 2,
        RobloxPrice = 100,
        Price = 10000,
        SellPrice = 5000,
        Gift = 1,
        PickTime = 0,
        CD = 0.8,
        Duration = 0,
        TimeUsed = 0,
    },
    [2] = {
        Index = 2,
        Item = "手电",
        DisplayName = "Flashlight",
        Icon = "rbxassetid://80944253490783",
        Model = "手电",
        Description = "A portable light source that helps you see in dark environments.",
        Type = 1,
        RobloxPrice = 40,
        Price = 4000,
        SellPrice = 2000,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        Duration = 30,
        TimeUsed = 0,
    },
    [3] = {
        Index = 4,
        Item = "荧光棒-红色",
        DisplayName = "Glow Stick - Red",
        Icon = "rbxassetid://117206965019901",
        Model = "荧光棒-红色",
        Description = "A disposable light source that emits a bright red glow, useful for marking areas or signaling.",
        Type = 1,
        RobloxPrice = 10,
        Price = 1000,
        SellPrice = 500,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        Duration = 30,
        TimeUsed = 1,
    },
    [4] = {
        Index = 5,
        Item = "铲子",
        DisplayName = "Shovel",
        Icon = "rbxassetid://117763824854828",
        Model = "铲子",
        Description = "A sturdy digging tool, can also be used as a blunt weapon in emergencies.",
        Type = 2,
        RobloxPrice = 50,
        Price = 5000,
        SellPrice = 2500,
        Gift = 1,
        PickTime = 0,
        CD = 1.5,
        Duration = 0,
        TimeUsed = 0,
    },
    [5] = {
        Index = 8,
        Item = "急救包",
        DisplayName = "First Aid Kit",
        Icon = "rbxassetid://116019405232413",
        Model = "急救包",
        Description = "A medical kit containing supplies to restore health and stop bleeding.",
        Type = 3,
        RobloxPrice = 30,
        Price = 3000,
        SellPrice = 1500,
        Gift = 1,
        PickTime = 0,
        CD = 120,
        Duration = 0,
        TimeUsed = 3,
    },
    [6] = {
        Index = 9,
        Item = "额外的背包",
        DisplayName = "Extra Backpack",
        Icon = "rbxassetid://98954413940819",
        Model = "额外的背包",
        Description = "Increases your carrying capacity for additional supplies.",
        Type = 3,
        RobloxPrice = 500,
        Price = 50000,
        SellPrice = 25000,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [7] = {
        Index = 10,
        Item = "传送装置",
        DisplayName = "Teleport Device",
        Icon = "rbxassetid://86586160503774",
        Model = "传送装置",
        Description = "A rare tool that instantly transports the user to a safe location.",
        Type = 3,
        RobloxPrice = 500,
        Price = 50000,
        SellPrice = 25000,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 1,
    },
    [8] = {
        Index = 1001,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Icon = "rbxassetid://140046656736906",
        Model = "破碎陶片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 10,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [9] = {
        Index = 1002,
        Item = "生锈铁钉",
        DisplayName = "Rusty Nail",
        Icon = "rbxassetid://140046656736906",
        Model = "生锈铁钉",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 12,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [10] = {
        Index = 1003,
        Item = "海玻璃碎片",
        DisplayName = "Sea Glass Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "海玻璃碎片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 15,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [11] = {
        Index = 1004,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Icon = "rbxassetid://140046656736906",
        Model = "石化木片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 18,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [12] = {
        Index = 1005,
        Item = "旧布条",
        DisplayName = "Old Cloth Strip",
        Icon = "rbxassetid://140046656736906",
        Model = "旧布条",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 20,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [13] = {
        Index = 1006,
        Item = "破旧绳索",
        DisplayName = "Worn Rope",
        Icon = "rbxassetid://140046656736906",
        Model = "破旧绳索",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 22,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [14] = {
        Index = 1007,
        Item = "骨头碎片",
        DisplayName = "Bone Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "骨头碎片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 25,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [15] = {
        Index = 1008,
        Item = "旧报纸残页",
        DisplayName = "Old Newspaper Scrap",
        Icon = "rbxassetid://140046656736906",
        Model = "旧报纸残页",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 28,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [16] = {
        Index = 1009,
        Item = "发霉书页",
        DisplayName = "Moldy Book Page",
        Icon = "rbxassetid://140046656736906",
        Model = "发霉书页",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 30,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [17] = {
        Index = 1010,
        Item = "普通贝壳",
        DisplayName = "Common Seashell",
        Icon = "rbxassetid://140046656736906",
        Model = "普通贝壳",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 32,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [18] = {
        Index = 1011,
        Item = "石英碎块",
        DisplayName = "Quartz Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "石英碎块",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 35,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [19] = {
        Index = 1012,
        Item = "旧铁扣",
        DisplayName = "Old Iron Buckle",
        Icon = "rbxassetid://140046656736906",
        Model = "旧铁扣",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 36,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [20] = {
        Index = 1013,
        Item = "黏土碎块",
        DisplayName = "Clay Chunk",
        Icon = "rbxassetid://140046656736906",
        Model = "黏土碎块",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 38,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [21] = {
        Index = 1014,
        Item = "普通矿石",
        DisplayName = "Common Ore",
        Icon = "rbxassetid://140046656736906",
        Model = "普通矿石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 40,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [22] = {
        Index = 1015,
        Item = "铜币",
        DisplayName = "Copper Coin",
        Icon = "rbxassetid://140046656736906",
        Model = "铜币",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 42,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [23] = {
        Index = 1016,
        Item = "木雕小偶",
        DisplayName = "Wooden Figurine",
        Icon = "rbxassetid://140046656736906",
        Model = "木雕小偶",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 45,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [24] = {
        Index = 1017,
        Item = "石头吊坠",
        DisplayName = "Stone Pendant",
        Icon = "rbxassetid://140046656736906",
        Model = "石头吊坠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 46,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [25] = {
        Index = 1018,
        Item = "小瓶碎玻璃",
        DisplayName = "Broken Glass Bottle",
        Icon = "rbxassetid://140046656736906",
        Model = "小瓶碎玻璃",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 48,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [26] = {
        Index = 1019,
        Item = "破损陶罐",
        DisplayName = "Damaged Clay Pot",
        Icon = "rbxassetid://140046656736906",
        Model = "破损陶罐",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 50,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [27] = {
        Index = 1020,
        Item = "银币",
        DisplayName = "Silver Coin",
        Icon = "rbxassetid://140046656736906",
        Model = "银币",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 60,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [28] = {
        Index = 1021,
        Item = "完整贝壳",
        DisplayName = "Intact Seashell",
        Icon = "rbxassetid://140046656736906",
        Model = "完整贝壳",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 65,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [29] = {
        Index = 1022,
        Item = "彩绘陶片",
        DisplayName = "Painted Pottery Shard",
        Icon = "rbxassetid://140046656736906",
        Model = "彩绘陶片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 70,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [30] = {
        Index = 1023,
        Item = "古代铜片",
        DisplayName = "Ancient Copper Piece",
        Icon = "rbxassetid://140046656736906",
        Model = "古代铜片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 75,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [31] = {
        Index = 1024,
        Item = "雕花骨饰",
        DisplayName = "Carved Bone Ornament",
        Icon = "rbxassetid://140046656736906",
        Model = "雕花骨饰",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 80,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [32] = {
        Index = 1025,
        Item = "奇异石纹",
        DisplayName = "Strange Stone Pattern",
        Icon = "rbxassetid://140046656736906",
        Model = "奇异石纹",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 85,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [33] = {
        Index = 1026,
        Item = "发光蘑菇",
        DisplayName = "Glowing Mushroom",
        Icon = "rbxassetid://140046656736906",
        Model = "发光蘑菇",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 90,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [34] = {
        Index = 1027,
        Item = "神秘水晶碎片",
        DisplayName = "Mysterious Crystal Shard",
        Icon = "rbxassetid://140046656736906",
        Model = "神秘水晶碎片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 95,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [35] = {
        Index = 1028,
        Item = "旧怀表",
        DisplayName = "Old Pocket Watch",
        Icon = "rbxassetid://140046656736906",
        Model = "旧怀表",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 100,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [36] = {
        Index = 1029,
        Item = "古地图残页",
        DisplayName = "Ancient Map Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "古地图残页",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 110,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [37] = {
        Index = 1030,
        Item = "雕刻木板",
        DisplayName = "Carved Wooden Board",
        Icon = "rbxassetid://140046656736906",
        Model = "雕刻木板",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 115,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [38] = {
        Index = 1031,
        Item = "彩色羽毛",
        DisplayName = "Colorful Feather",
        Icon = "rbxassetid://140046656736906",
        Model = "彩色羽毛",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 120,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [39] = {
        Index = 1032,
        Item = "珍珠",
        DisplayName = "Pearl",
        Icon = "rbxassetid://140046656736906",
        Model = "珍珠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 125,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [40] = {
        Index = 1033,
        Item = "银制戒指",
        DisplayName = "Silver Ring",
        Icon = "rbxassetid://140046656736906",
        Model = "银制戒指",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 130,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [41] = {
        Index = 1034,
        Item = "古代陶器",
        DisplayName = "Ancient Pottery",
        Icon = "rbxassetid://140046656736906",
        Model = "古代陶器",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 135,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [42] = {
        Index = 1035,
        Item = "兽角",
        DisplayName = "Beast Horn",
        Icon = "rbxassetid://140046656736906",
        Model = "兽角",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 140,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [43] = {
        Index = 1036,
        Item = "稀有化石",
        DisplayName = "Rare Fossil",
        Icon = "rbxassetid://140046656736906",
        Model = "稀有化石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 145,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [44] = {
        Index = 1037,
        Item = "古代石刻",
        DisplayName = "Ancient Stone Carving",
        Icon = "rbxassetid://140046656736906",
        Model = "古代石刻",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 150,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [45] = {
        Index = 1038,
        Item = "金币",
        DisplayName = "Gold Coin",
        Icon = "rbxassetid://140046656736906",
        Model = "金币",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 160,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [46] = {
        Index = 1039,
        Item = "发光水晶",
        DisplayName = "Glowing Crystal",
        Icon = "rbxassetid://140046656736906",
        Model = "发光水晶",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 170,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [47] = {
        Index = 1040,
        Item = "宝石碎片",
        DisplayName = "Gem Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "宝石碎片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 180,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [48] = {
        Index = 1041,
        Item = "古代金属片",
        DisplayName = "Ancient Metal Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "古代金属片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 190,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [49] = {
        Index = 1042,
        Item = "古人面具",
        DisplayName = "Ancient Mask",
        Icon = "rbxassetid://140046656736906",
        Model = "古人面具",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 200,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [50] = {
        Index = 1043,
        Item = "翡翠碎块",
        DisplayName = "Jade Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "翡翠碎块",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 220,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [51] = {
        Index = 1044,
        Item = "奇异骨骼",
        DisplayName = "Strange Skeleton",
        Icon = "rbxassetid://140046656736906",
        Model = "奇异骨骼",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 240,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [52] = {
        Index = 1045,
        Item = "兽皮卷轴",
        DisplayName = "Animal Hide Scroll",
        Icon = "rbxassetid://140046656736906",
        Model = "兽皮卷轴",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 260,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [53] = {
        Index = 1046,
        Item = "罕见珍珠",
        DisplayName = "Rare Pearl",
        Icon = "rbxassetid://140046656736906",
        Model = "罕见珍珠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 280,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [54] = {
        Index = 1047,
        Item = "银制杯盏",
        DisplayName = "Silver Goblet",
        Icon = "rbxassetid://140046656736906",
        Model = "银制杯盏",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 300,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [55] = {
        Index = 1048,
        Item = "古代青铜剑残片",
        DisplayName = "Ancient Bronze Sword Shard",
        Icon = "rbxassetid://140046656736906",
        Model = "古代青铜剑残片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 320,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [56] = {
        Index = 1049,
        Item = "玛瑙石",
        DisplayName = "Agate Stone",
        Icon = "rbxassetid://140046656736906",
        Model = "玛瑙石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 340,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [57] = {
        Index = 1050,
        Item = "黄金吊坠",
        DisplayName = "Golden Pendant",
        Icon = "rbxassetid://140046656736906",
        Model = "黄金吊坠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 360,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [58] = {
        Index = 1051,
        Item = "水晶球碎裂物",
        DisplayName = "Shattered Crystal Ball",
        Icon = "rbxassetid://140046656736906",
        Model = "水晶球碎裂物",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 380,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [59] = {
        Index = 1052,
        Item = "神秘石板",
        DisplayName = "Mysterious Stone Tablet",
        Icon = "rbxassetid://140046656736906",
        Model = "神秘石板",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 400,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [60] = {
        Index = 1053,
        Item = "黄金杯",
        DisplayName = "Golden Chalice",
        Icon = "rbxassetid://140046656736906",
        Model = "黄金杯",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 500,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [61] = {
        Index = 1054,
        Item = "红宝石",
        DisplayName = "Ruby",
        Icon = "rbxassetid://140046656736906",
        Model = "红宝石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 550,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [62] = {
        Index = 1055,
        Item = "蓝宝石",
        DisplayName = "Sapphire",
        Icon = "rbxassetid://140046656736906",
        Model = "蓝宝石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 600,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [63] = {
        Index = 1056,
        Item = "古代王冠残片",
        DisplayName = "Ancient Crown Fragment",
        Icon = "rbxassetid://140046656736906",
        Model = "古代王冠残片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 650,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [64] = {
        Index = 1057,
        Item = "巨型珍珠",
        DisplayName = "Giant Pearl",
        Icon = "rbxassetid://140046656736906",
        Model = "巨型珍珠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 700,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [65] = {
        Index = 1058,
        Item = "神秘法典",
        DisplayName = "Mysterious Codex",
        Icon = "rbxassetid://140046656736906",
        Model = "神秘法典",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 750,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [66] = {
        Index = 1059,
        Item = "龙骨",
        DisplayName = "Dragon Bone",
        Icon = "rbxassetid://140046656736906",
        Model = "龙骨",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 800,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [67] = {
        Index = 1060,
        Item = "魔化水晶",
        DisplayName = "Enchanted Crystal",
        Icon = "rbxassetid://140046656736906",
        Model = "魔化水晶",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 850,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [68] = {
        Index = 1061,
        Item = "古代神像碎片",
        DisplayName = "Ancient Idol Shard",
        Icon = "rbxassetid://140046656736906",
        Model = "古代神像碎片",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 900,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [69] = {
        Index = 1062,
        Item = "黄金宝箱残骸",
        DisplayName = "Golden Chest Remains",
        Icon = "rbxassetid://140046656736906",
        Model = "黄金宝箱残骸",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 950,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [70] = {
        Index = 1063,
        Item = "黑曜石核心",
        DisplayName = "Obsidian Core",
        Icon = "rbxassetid://140046656736906",
        Model = "黑曜石核心",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1000,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [71] = {
        Index = 1064,
        Item = "纯金权杖",
        DisplayName = "Pure Gold Scepter",
        Icon = "rbxassetid://140046656736906",
        Model = "纯金权杖",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1200,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [72] = {
        Index = 1065,
        Item = "祖母绿巨石",
        DisplayName = "Emerald Boulder",
        Icon = "rbxassetid://140046656736906",
        Model = "祖母绿巨石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1300,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [73] = {
        Index = 1066,
        Item = "凤凰羽",
        DisplayName = "Phoenix Feather",
        Icon = "rbxassetid://140046656736906",
        Model = "凤凰羽",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1400,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [74] = {
        Index = 1067,
        Item = "神秘符文石",
        DisplayName = "Rune Stone",
        Icon = "rbxassetid://140046656736906",
        Model = "神秘符文石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1500,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [75] = {
        Index = 1068,
        Item = "古代神王戒",
        DisplayName = "Ancient King’s Ring",
        Icon = "rbxassetid://140046656736906",
        Model = "古代神王戒",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1600,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [76] = {
        Index = 1069,
        Item = "龙之心石",
        DisplayName = "Dragon Heartstone",
        Icon = "rbxassetid://140046656736906",
        Model = "龙之心石",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1700,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [77] = {
        Index = 1070,
        Item = "天青宝珠",
        DisplayName = "Azure Orb",
        Icon = "rbxassetid://140046656736906",
        Model = "天青宝珠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1800,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [78] = {
        Index = 1071,
        Item = "时间之沙瓶",
        DisplayName = "Hourglass of Time",
        Icon = "rbxassetid://140046656736906",
        Model = "时间之沙瓶",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1900,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
    [79] = {
        Index = 1072,
        Item = "遗失的帝王皇冠",
        DisplayName = "Lost Imperial Crown",
        Icon = "rbxassetid://140046656736906",
        Model = "遗失的帝王皇冠",
        Description = nil,
        Type = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 2000,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        Duration = 0,
        TimeUsed = 0,
    },
}

-- 辅助函数
function ItemConfig:GetByIndex(index)
    for i, item in pairs(self.Data) do
        if item.Index == index then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByItem(value)
    for i, item in pairs(self.Data) do
        if item.Item == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDisplayName(value)
    for i, item in pairs(self.Data) do
        if item.DisplayName == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByIcon(value)
    for i, item in pairs(self.Data) do
        if item.Icon == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByModel(value)
    for i, item in pairs(self.Data) do
        if item.Model == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDescription(value)
    for i, item in pairs(self.Data) do
        if item.Description == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByType(value)
    for i, item in pairs(self.Data) do
        if item.Type == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByRobloxPrice(value)
    for i, item in pairs(self.Data) do
        if item.RobloxPrice == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByPrice(value)
    for i, item in pairs(self.Data) do
        if item.Price == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetBySellPrice(value)
    for i, item in pairs(self.Data) do
        if item.SellPrice == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByGift(value)
    for i, item in pairs(self.Data) do
        if item.Gift == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByPickTime(value)
    for i, item in pairs(self.Data) do
        if item.PickTime == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByCD(value)
    for i, item in pairs(self.Data) do
        if item.CD == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDuration(value)
    for i, item in pairs(self.Data) do
        if item.Duration == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByTimeUsed(value)
    for i, item in pairs(self.Data) do
        if item.TimeUsed == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetAll()
    return self.Data
end

function ItemConfig:GetCount()
    local count = 0
    for _ in pairs(self.Data) do
        count = count + 1
    end
    return count
end

function ItemConfig:GetAllByType(itemType)
    local result = {}
    for i, item in pairs(self.Data) do
        if item.Type == itemType then
            table.insert(result, item)
        end
    end
    return result
end

return ItemConfig