
local ItemConfig = {}

ItemConfig.Data = {
    [1] = {
        ItemId = 101,
        Item = "手电",
        DisplayName = "Flashlight",
        Type = 1,
        Quality = nil,
        Duration = 300,
        TimeUsed = 0,
        Weight = 1,
        RobloxPrice = 40,
        Price = 4000,
        SellPrice = 300,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        DropSources = "Shop",
        Icon = "rbxassetid://80944253490783",
        Model = "手电",
        Description = "Can be used to illuminate in the dark.",
    },
    [2] = {
        ItemId = 102,
        Item = "荧光棒-红色",
        DisplayName = "Glow Stick - Red",
        Type = 1,
        Quality = nil,
        Duration = 100,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 10,
        Price = 1000,
        SellPrice = 240,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        DropSources = "Shop",
        Icon = "rbxassetid://117206965019901",
        Model = "荧光棒-红色",
        Description = "Can be used to illuminate in the dark.",
    },
    [3] = {
        ItemId = 201,
        Item = "刺刀",
        DisplayName = "Bayonet",
        Type = 2,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 3,
        RobloxPrice = 100,
        Price = 10000,
        SellPrice = 2400,
        Gift = 1,
        PickTime = 0,
        CD = 0.8,
        DropSources = "Shop",
        Icon = "rbxassetid://94897262399463",
        Model = "刺刀",
        Description = "Increases damage +20,Can attack monsters and objects.",
    },
    [4] = {
        ItemId = 202,
        Item = "铲子",
        DisplayName = "Shovel",
        Type = 2,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 4.5,
        RobloxPrice = 50,
        Price = 5000,
        SellPrice = 1200,
        Gift = 1,
        PickTime = 0,
        CD = 1.5,
        DropSources = "Shop",
        Icon = "rbxassetid://117763824854828",
        Model = "铲子",
        Description = "Increases damage +10,can dig the ground and attack monsters.",
    },
    [5] = {
        ItemId = 203,
        Item = "镐子",
        DisplayName = "Pickaxe",
        Type = 2,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 4,
        RobloxPrice = 50,
        Price = 5000,
        SellPrice = 1200,
        Gift = 1,
        PickTime = 0,
        CD = 1.5,
        DropSources = "Shop",
        Icon = "rbxassetid://92138284892917",
        Model = "镐子",
        Description = "Increases damage +10,Can mine ores and attack monsters.",
    },
    [6] = {
        ItemId = 302,
        Item = "额外的背包",
        DisplayName = "Extra Backpack",
        Type = 3,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 5,
        RobloxPrice = 500,
        Price = 50000,
        SellPrice = 8000,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        DropSources = "Shop",
        Icon = "rbxassetid://98954413940819",
        Model = "额外的背包",
        Description = "Increases inventory space +3 slots.",
    },
    [7] = {
        ItemId = 303,
        Item = "传送装置",
        DisplayName = "Teleport Device",
        Type = 3,
        Quality = nil,
        Duration = 0,
        TimeUsed = 1,
        Weight = 3.5,
        RobloxPrice = 500,
        Price = 50000,
        SellPrice = 1200,
        Gift = 1,
        PickTime = 0,
        CD = 0,
        DropSources = "Shop",
        Icon = "rbxassetid://86586160503774",
        Model = "传送装置",
        Description = "Can be used to teleport yourself and nearby allies back to a safe zone.",
    },
    [8] = {
        ItemId = 304,
        Item = "宝库钥匙",
        DisplayName = "Chest Key",
        Type = 3,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island Clue Sources",
        Icon = "rbxassetid://116356552356986",
        Model = "宝库钥匙",
        Description = nil,
    },
    [9] = {
        ItemId = 501,
        Item = "普通宝箱",
        DisplayName = "Common Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 3,
        CD = 0,
        DropSources = nil,
        Icon = "79444189408046",
        Model = "宝箱1",
        Description = nil,
    },
    [10] = {
        ItemId = 502,
        Item = "黄金宝箱",
        DisplayName = "Golden Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 5,
        CD = 0,
        DropSources = nil,
        Icon = "79444189408046",
        Model = "宝箱2",
        Description = nil,
    },
    [11] = {
        ItemId = 503,
        Item = "炫彩宝箱",
        DisplayName = "Shiny Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 8,
        CD = 0,
        DropSources = nil,
        Icon = "79444189408046",
        Model = "宝箱3",
        Description = nil,
    },
    [12] = {
        ItemId = 504,
        Item = "炫彩宝箱",
        DisplayName = "Shiny Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 8,
        CD = 0,
        DropSources = nil,
        Icon = "79444189408046",
        Model = "宝箱4",
        Description = nil,
    },
    [13] = {
        ItemId = 505,
        Item = "炫彩宝箱",
        DisplayName = "Shiny Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 8,
        CD = 0,
        DropSources = nil,
        Icon = "79444189408046",
        Model = "宝箱5",
        Description = nil,
    },
    [14] = {
        ItemId = 506,
        Item = "木桶",
        DisplayName = "Shiny Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 1,
        CD = 0,
        DropSources = nil,
        Icon = nil,
        Model = "木桶",
        Description = nil,
    },
    [15] = {
        ItemId = 507,
        Item = "石棺",
        DisplayName = "Shiny Chest",
        Type = 5,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 1,
        CD = 0,
        DropSources = nil,
        Icon = "89337655253380",
        Model = "石棺",
        Description = nil,
    },
    [16] = {
        ItemId = 601,
        Item = "土堆",
        DisplayName = "Dirt Mound",
        Type = 6,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = nil,
        Icon = nil,
        Model = "土堆",
        Description = nil,
    },
    [17] = {
        ItemId = 602,
        Item = "散落的土堆",
        DisplayName = "Scattered Dirt Mounds",
        Type = 6,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = nil,
        Icon = nil,
        Model = "散落的土堆",
        Description = nil,
    },
    [18] = {
        ItemId = 603,
        Item = "矿石",
        DisplayName = "Ore",
        Type = 6,
        Quality = nil,
        Duration = 0,
        TimeUsed = 5,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = nil,
        Icon = "rbxassetid://131450236273906",
        Model = "矿石",
        Description = nil,
    },
    [19] = {
        ItemId = 701,
        Item = "蘑菇",
        DisplayName = "Mushroom（65% +30HP）",
        Type = 7,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 1.5,
        CD = 0,
        DropSources = nil,
        Icon = "rbxassetid://125683003473301",
        Model = "蘑菇",
        Description = nil,
    },
    [20] = {
        ItemId = 801,
        Item = "急救包",
        DisplayName = "First Aid Kit",
        Type = 8,
        Quality = nil,
        Duration = 0,
        TimeUsed = 3,
        Weight = 2.5,
        RobloxPrice = 30,
        Price = 3000,
        SellPrice = 1360,
        Gift = 1,
        PickTime = 0,
        CD = 1.5,
        DropSources = "Shop",
        Icon = "rbxassetid://116019405232413",
        Model = "急救包",
        Description = "Restores some health,can be used 3 times.",
    },
    [21] = {
        ItemId = 10011,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 1,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [22] = {
        ItemId = 10012,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 2,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 7,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [23] = {
        ItemId = 10013,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 3,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 9,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [24] = {
        ItemId = 10014,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 4,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 11,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [25] = {
        ItemId = 10015,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 5,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 13,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [26] = {
        ItemId = 10016,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 6,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 15,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [27] = {
        ItemId = 10017,
        Item = "破碎陶片",
        DisplayName = "Broken Pottery Shard",
        Type = 4,
        Quality = 7,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 17,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138603713864045",
        Model = "破碎陶片",
        Description = nil,
    },
    [28] = {
        ItemId = 1002,
        Item = "生锈铁钉",
        DisplayName = "Rusty Nail",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.2,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 10,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://82277829138618",
        Model = "生锈铁钉",
        Description = "Material used for upgrading talents.",
    },
    [29] = {
        ItemId = 1003,
        Item = "海玻璃碎片",
        DisplayName = "Sea Glass Fragment",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://110975175622147",
        Model = "海玻璃碎片",
        Description = nil,
    },
    [30] = {
        ItemId = 10041,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 1,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 10,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [31] = {
        ItemId = 10042,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 2,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 13,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [32] = {
        ItemId = 10043,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 3,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 16,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [33] = {
        ItemId = 10044,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 4,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 19,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [34] = {
        ItemId = 10045,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 5,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 22,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [35] = {
        ItemId = 10046,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 6,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 25,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [36] = {
        ItemId = 10047,
        Item = "石化木片",
        DisplayName = "Petrified Wood Chip",
        Type = 4,
        Quality = 7,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 28,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://72739379270245",
        Model = "石化木片",
        Description = "Material used for upgrading talents.",
    },
    [37] = {
        ItemId = 1005,
        Item = "旧布条",
        DisplayName = "Old Cloth Strip",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.2,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://89935448987523",
        Model = "旧布条",
        Description = "Material used for upgrading talents.",
    },
    [38] = {
        ItemId = 1006,
        Item = "破旧绳索",
        DisplayName = "Worn Rope",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://122411307036488",
        Model = "破旧绳索",
        Description = nil,
    },
    [39] = {
        ItemId = 1007,
        Item = "骨头碎片",
        DisplayName = "Bone Fragment",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://105576003572190",
        Model = "骨头碎片",
        Description = "Material used for upgrading talents.",
    },
    [40] = {
        ItemId = 1008,
        Item = "旧报纸残页",
        DisplayName = "Old Newspaper Scrap",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.1,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://73093497229758",
        Model = "旧报纸残页",
        Description = nil,
    },
    [41] = {
        ItemId = 1009,
        Item = "信封",
        DisplayName = "Envelope",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.1,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 15,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://138713655406841",
        Model = "信封",
        Description = nil,
    },
    [42] = {
        ItemId = 1010,
        Item = "陶罐",
        DisplayName = "Clay Pot",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 2,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 30,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://96684574627137",
        Model = "陶罐",
        Description = "Material used for upgrading talents.",
    },
    [43] = {
        ItemId = 1011,
        Item = "海盗帽",
        DisplayName = "Pirate Hat",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.8,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 100,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://75979111313340",
        Model = "海盗帽",
        Description = "Material used for upgrading talents.",
    },
    [44] = {
        ItemId = 1012,
        Item = "提灯",
        DisplayName = "Lantern",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 2.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 150,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://86068885165137",
        Model = "提灯",
        Description = "Material used for upgrading talents.",
    },
    [45] = {
        ItemId = 1013,
        Item = "大葱",
        DisplayName = "Green Onion",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 15,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://120349324917743",
        Model = "大葱",
        Description = "Material used for upgrading talents.",
    },
    [46] = {
        ItemId = 1014,
        Item = "扇子",
        DisplayName = "Fan",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.2,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 30,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://100156804426081",
        Model = "扇子",
        Description = "Material used for upgrading talents.",
    },
    [47] = {
        ItemId = 1015,
        Item = "木桶",
        DisplayName = "Wooden Barrel",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 4,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 80,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://117483365334798",
        Model = "木桶",
        Description = "Material used for upgrading talents.",
    },
    [48] = {
        ItemId = 1016,
        Item = "水壶",
        DisplayName = "Water Kettle",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1.8,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 40,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://107365993175298",
        Model = "水壶",
        Description = "Material used for upgrading talents.",
    },
    [49] = {
        ItemId = 1017,
        Item = "木条",
        DisplayName = "Wooden Plank",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 15,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://78896655282067",
        Model = "木条",
        Description = "Material used for upgrading talents.",
    },
    [50] = {
        ItemId = 1018,
        Item = "钱袋",
        DisplayName = "Money Bag",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 450,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://85828547583727",
        Model = "钱袋",
        Description = "Material used for upgrading talents.",
    },
    [51] = {
        ItemId = 1019,
        Item = "面具",
        DisplayName = "Mask",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.6,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 60,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://85922917375016",
        Model = "面具",
        Description = nil,
    },
    [52] = {
        ItemId = 1020,
        Item = "鬼脸娃娃",
        DisplayName = "Grimace Doll",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 80,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://86205452605963",
        Model = "鬼脸娃娃",
        Description = "Material used for upgrading talents.",
    },
    [53] = {
        ItemId = 1021,
        Item = "靴子",
        DisplayName = "Boots",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 160,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://83774438054930",
        Model = "靴子",
        Description = "Material used for upgrading talents.",
    },
    [54] = {
        ItemId = 1022,
        Item = "魔法帽",
        DisplayName = "Wizard Hat",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.8,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 160,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://104600101847403",
        Model = "魔法帽",
        Description = "Material used for upgrading talents.",
    },
    [55] = {
        ItemId = 1023,
        Item = "手套",
        DisplayName = "Gloves",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.3,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 160,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://135724777590724",
        Model = "手套",
        Description = nil,
    },
    [56] = {
        ItemId = 1024,
        Item = "生锈的齿轮",
        DisplayName = "Rusty Gear",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1.2,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 20,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://90347812810054",
        Model = "生锈的齿轮",
        Description = "Material used for upgrading talents.",
    },
    [57] = {
        ItemId = 1025,
        Item = "兽角",
        DisplayName = "Beast Horn",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.9,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://120912130598306",
        Model = "兽角",
        Description = nil,
    },
    [58] = {
        ItemId = 1026,
        Item = "野兽骸骨",
        DisplayName = "Beast Skeleton",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 3.5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://100485402089375",
        Model = "野兽骸骨",
        Description = "Material used for upgrading talents.",
    },
    [59] = {
        ItemId = 1027,
        Item = "粘液",
        DisplayName = "Slime",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 10,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://94723848723446",
        Model = "粘液",
        Description = nil,
    },
    [60] = {
        ItemId = 1028,
        Item = "一瓶粘液",
        DisplayName = "Vial of Slime",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 1.2,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 30,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://88068426664096",
        Model = "一瓶粘液",
        Description = "Material used for upgrading talents.",
    },
    [61] = {
        ItemId = 1029,
        Item = "潜水头盔",
        DisplayName = "Diving Helmet",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 5,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 220,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://123592447775167",
        Model = "潜水头盔",
        Description = "Material used for upgrading talents.",
    },
    [62] = {
        ItemId = 1030,
        Item = "船锚",
        DisplayName = "Anchor",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 8,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 450,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://86963789369428",
        Model = "船锚",
        Description = "Material used for upgrading talents.",
    },
    [63] = {
        ItemId = 1031,
        Item = "船舵",
        DisplayName = "Ship's Wheel",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 6,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 450,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://91850687518910",
        Model = "船舵",
        Description = "Material used for upgrading talents.",
    },
    [64] = {
        ItemId = 1032,
        Item = "发霉书页",
        DisplayName = "Moldy Book Page",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0.1,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 10,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://81176096156968",
        Model = "发霉书页",
        Description = "Material used for upgrading talents.",
    },
    [65] = {
        ItemId = 1033,
        Item = "枪",
        DisplayName = "Gun",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 8,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 1350,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://122810694378500",
        Model = "枪",
        Description = "Material used for upgrading talents.",
    },
    [66] = {
        ItemId = 1034,
        Item = "刀",
        DisplayName = "Knife",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 8,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 3000,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://134783722097358",
        Model = "刀",
        Description = "Material used for upgrading talents.",
    },
    [67] = {
        ItemId = 1035,
        Item = "龙珠",
        DisplayName = "Dragon Orb",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 15,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 5000,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island Peak",
        Icon = "rbxassetid://103874659967279",
        Model = "龙珠",
        Description = "Material used for upgrading talents.",
    },
    [68] = {
        ItemId = 1036,
        Item = "红宝石",
        DisplayName = "Ruby Gem",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 15,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 380,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dinosaur Island Monster Loot",
        Icon = "rbxassetid://94532553074007",
        Model = "红宝石",
        Description = nil,
    },
    [69] = {
        ItemId = 1037,
        Item = "蓝宝石",
        DisplayName = "Sapphire Gem",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 15,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 380,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "The Dino Island Mine",
        Icon = "rbxassetid://95443518196844",
        Model = "蓝宝石",
        Description = "Material used for upgrading talents.",
    },
    [70] = {
        ItemId = 1038,
        Item = "心形宝石",
        DisplayName = "Heart Gem",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 15,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 380,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "The Dino Island Treasure Trove",
        Icon = "rbxassetid://108864196858289",
        Model = "心形宝石",
        Description = "Material used for upgrading talents.",
    },
    [71] = {
        ItemId = 1039,
        Item = "金币小",
        DisplayName = "Gold",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://102600054562573",
        Model = "金币小",
        Description = nil,
    },
    [72] = {
        ItemId = 1040,
        Item = "金币中",
        DisplayName = "Gold",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://102600054562573",
        Model = "金币中",
        Description = nil,
    },
    [73] = {
        ItemId = 1041,
        Item = "金币大",
        DisplayName = "Gold",
        Type = 4,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 0,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "Dino Island",
        Icon = "rbxassetid://102600054562573",
        Model = "金币大",
        Description = nil,
    },
    [74] = {
        ItemId = 10001,
        Item = "地刺",
        DisplayName = "Heart Gem",
        Type = 10,
        Quality = nil,
        Duration = 0,
        TimeUsed = 0,
        Weight = 15,
        RobloxPrice = 0,
        Price = 0,
        SellPrice = 0,
        Gift = 0,
        PickTime = 0,
        CD = 0,
        DropSources = "The Dino Island Treasure Trove",
        Icon = "rbxassetid://108864196858289",
        Model = "地刺",
        Description = "Material used for upgrading talents.",
    },
}

-- 辅助函数
function ItemConfig:GetByIndex(index)
    return self.Data[index]
end

function ItemConfig:GetByItemId(value)
    for i, item in pairs(self.Data) do
        if item.ItemId == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByItem(value)
    for i, item in pairs(self.Data) do
        if item.Item == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDisplayName(value)
    for i, item in pairs(self.Data) do
        if item.DisplayName == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByType(value)
    for i, item in pairs(self.Data) do
        if item.Type == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByQuality(value)
    for i, item in pairs(self.Data) do
        if item.Quality == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDuration(value)
    for i, item in pairs(self.Data) do
        if item.Duration == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByTimeUsed(value)
    for i, item in pairs(self.Data) do
        if item.TimeUsed == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByWeight(value)
    for i, item in pairs(self.Data) do
        if item.Weight == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByRobloxPrice(value)
    for i, item in pairs(self.Data) do
        if item.RobloxPrice == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByPrice(value)
    for i, item in pairs(self.Data) do
        if item.Price == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetBySellPrice(value)
    for i, item in pairs(self.Data) do
        if item.SellPrice == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByGift(value)
    for i, item in pairs(self.Data) do
        if item.Gift == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByPickTime(value)
    for i, item in pairs(self.Data) do
        if item.PickTime == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByCD(value)
    for i, item in pairs(self.Data) do
        if item.CD == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDropSources(value)
    for i, item in pairs(self.Data) do
        if item.DropSources == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByIcon(value)
    for i, item in pairs(self.Data) do
        if item.Icon == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByModel(value)
    for i, item in pairs(self.Data) do
        if item.Model == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetByDescription(value)
    for i, item in pairs(self.Data) do
        if item.Description == value then
            return item
        end
    end
    return nil
end

function ItemConfig:GetAll()
    return self.Data
end

function ItemConfig:GetCount()
    local count = 0
    for _ in pairs(self.Data) do
        count = count + 1
    end
    return count
end

function ItemConfig:GetAllByType(itemType)
    local result = {}
    for i, item in pairs(self.Data) do
        if item.Type == itemType then
            table.insert(result, item)
        end
    end
    return result
end

return ItemConfig