local LanguageConfig = {}
local Text = {
	[10001] = {zh_cn = "提示", en_us = "Notice"},
	[10002] = {zh_cn = "确定", en_us = "Confirm"},
	[10003] = {zh_cn = "取消", en_us = "Cancel"},
	[10004] = {zh_cn = "启航", en_us = "Set Sail"},
	[10005] = {zh_cn = "止航", en_us = "Stop Sailing"},
	[10006] = {zh_cn = "添加部件", en_us = "Add Part"},
	[10007] = {zh_cn = "金币", en_us = "Gold"},
	[10008] = {zh_cn = "抽奖", en_us = "Draw"},
	[10009] = {zh_cn = "分解", en_us = "Dismantle"},
	[10010] = {zh_cn = "分解可获得%s金币,是否分解?", en_us = "Dismantling will give you %s gold. Proceed?"},
	[10011] = {zh_cn = "恭喜你获得了: %s", en_us = "Congratulations! You received: %s"},
	[10012] = {zh_cn = "你失去了: %s", en_us = "You lost: %s"},
	[10013] = {zh_cn = "生命", en_us = "Health"},
	[10014] = {zh_cn = "速度", en_us = "Speed"},
	[10015] = {zh_cn = "冷却时间未到", en_us = "Cooldown not yet finished"},
	[10016] = {zh_cn = "你获得了已有的船部件%s，已自动分解", en_us = "You received a duplicate ship part %s. It has been automatically dismantled."},
	[10017] = {zh_cn = "添加部件失败，船不存在", en_us = "Failed to add part: Ship does not exist"},
	[10018] = {zh_cn = "添加部件失败，玩家不存在", en_us = "Failed to add part: Player does not exist"},
	[10019] = {zh_cn = "部件添加成功", en_us = "Part added successfully"},
	[10020] = {zh_cn = "船已存在", en_us = "Ship already exists"},
	[10021] = {zh_cn = "玩家没有可用的船主部件", en_us = "Player has no usable ship hull part"},
	[10022] = {zh_cn = "船组装成功", en_us = "Ship assembled successfully"},
	[10023] = {zh_cn = "你正在使用它，不能分解", en_us = "You're using this item. It cannot be dismantled."},
	[10024] = {zh_cn = "是否将出生地设置为本区域?", en_us = "Set this area as your spawn point?"},
	[10025] = {zh_cn = "背包", en_us = "Backpack"},
	[10026] = {zh_cn = "玩家", en_us = "Player"},
	[10027] = {zh_cn = "赠送", en_us = "Gift"},
	[10028] = {zh_cn = "赠送成功", en_us = "Gift sent successfully"},
	[10029] = {zh_cn = "选择数量", en_us = "Select quantity"},
	[10030] = {zh_cn = "不能赠送自己", en_us = "Cannot gift to yourself"},
	[10031] = {zh_cn = "%s赠送给你一些物品", en_us = "%s has gifted you some items"},
	[10032] = {zh_cn = "没找到玩家", en_us = "Player not found"},
	[10033] = {zh_cn = "玩家列表", en_us = "Player List"},
	[10035] = {zh_cn = "欢迎你，请选择你的操作", en_us = "Welcome! Choose your action."},
	[10036] = {zh_cn = "占领", en_us = "Occupy"},
	[10037] = {zh_cn = "正在占领中，请不要移动...", en_us = "Occupying... Please don't move."},
	[10038] = {zh_cn = "恭喜你，成功占领%s", en_us = "Congratulations! You have occupied %s."},
	[10039] = {zh_cn = "玩家%s成功占领了%s", en_us = "Player %s has successfully occupied %s."},
	[10040] = {zh_cn = "登岛", en_us = "Land"},
	[10041] = {zh_cn = "交费%s", en_us = "Pay %s"},
	[10042] = {zh_cn = "%s岛屿错误", en_us = "%s Island Error"},
	[10043] = {zh_cn = "你不是岛主，不能设置出生点", en_us = "You're not the island owner. Cannot set spawn."},
	[10044] = {zh_cn = "金币不够", en_us = "Not enough gold"},
	[10045] = {zh_cn = "你收到玩家%s为登陆%s而付的%s金币", en_us = "You received %s gold from player %s for landing on %s"},
	[10046] = {zh_cn = "此岛已被%s占领，请选择你的操作", en_us = "This island is occupied by %s. Choose your action."},
	[10047] = {zh_cn = "岛主", en_us = "Island Owner"},
	[10048] = {zh_cn = "离线期间,你总共获得%s金币的收益", en_us = "You earned %s gold while offline"},
	[10049] = {zh_cn = "你登陆了%s", en_us = "You landed on %s"},
	[10050] = {zh_cn = "欢迎你进入游戏", en_us = "Welcome to the game"},
	[10051] = {zh_cn = "运气太衰，这是个空箱子", en_us = "Unlucky! It's an empty chest."},
	[10052] = {zh_cn = "速度", en_us = "Speed"},
	[10053] = {zh_cn = "生命", en_us = "Health"},
	[10054] = {zh_cn = "幸运", en_us = "Luck"},
	[10055] = {zh_cn = "购买成功", en_us = "Purchase Successful"},
	[10056] = {zh_cn = "金币不足", en_us = "Insufficient Gold"},
	[10057] = {zh_cn = "系统错误", en_us = "System Error"},
	[10058] = {zh_cn = "你不是岛主，不能购买箭塔", en_us = "You're not the island owner. Cannot buy towers."},
	[10059] = {zh_cn = "已达到能购买的最大箭塔数量", en_us = "Maximum number of towers reached"},
	[10060] = {zh_cn = "拆除成功", en_us = "Demolition Successful"},
	[10061] = {zh_cn = "你不是岛主，不能拆除箭塔", en_us = "You're not the island owner. Cannot demolish tower."},
	[10062] = {zh_cn = "基础箭塔", en_us = "Basic Tower"},
	[10063] = {zh_cn = "中级箭塔", en_us = "Intermediate Tower"},
	[10064] = {zh_cn = "高级箭塔", en_us = "Advanced Tower"},
	[10065] = {zh_cn = "占领失败", en_us = "Occupation Failed"},
	[10066] = {zh_cn = "岛屿管理", en_us = "Island Management"},
	[10067] = {zh_cn = "我的岛屿", en_us = "My Islands"},
	[10068] = {zh_cn = "箭塔数量", en_us = "Number of Towers"},
	[10069] = {zh_cn = "总收益", en_us = "Total Earnings"},
	[10070] = {zh_cn = "箭塔管理", en_us = "Tower Management"},
	[10071] = {zh_cn = "不可用", en_us = "Unavailable"},
	[10072] = {zh_cn = "此岛屿不支持", en_us = "This island is not supported"},
	[10073] = {zh_cn = "伤害", en_us = "Damage"},
	[10074] = {zh_cn = "你是否要拆除此箭塔？", en_us = "Do you want to remove this tower?"},
	[10075] = {zh_cn = "购买箭塔", en_us = "Buy Tower"},
	[10076] = {zh_cn = "你还没有拥有任何岛屿", en_us = "You don't own any islands yet"},
	[10077] = {zh_cn = "选择箭塔类型", en_us = "Select Tower Type"},
	[10078] = {zh_cn = "当前效果", en_us = "Current Effect"},
	[10079] = {zh_cn = "%s占领%s失败", en_us = "%s failed to occupy %s"},
	[10080] = {zh_cn = "%s成功占领%s", en_us = "%s successfully occupied %s"},
	[10081] = {zh_cn = "%s开始攻打%s", en_us = "%s has started attacking %s"},
	[10082] = {zh_cn = "无名岛", en_us = "Unnamed Island"},
	[10083] = {zh_cn = "你是否登船", en_us = "Do you want to board the ship?"},
	[10084] = {zh_cn = "排行榜", en_us = "Leaderboard"},
	[10085] = {zh_cn = "总航行距离", en_us = "Total Sailing Distance"},
	[10086] = {zh_cn = "单次航行距离", en_us = "Single Trip Distance"},
	[10087] = {zh_cn = "单次航行天数", en_us = "Single Trip Days"},
	[10088] = {zh_cn = "未上榜", en_us = "Not Ranked"},
	[10089] = {zh_cn = "我的排名: ", en_us = "My Ranking: "},
	[10090] = {zh_cn = "总航行天数", en_us = "Total Sailing Days"},
	[10091] = {zh_cn = "排名", en_us = "Rank"},
	[10092] = {zh_cn = "商城", en_us = "Store"},
	[10093] = {zh_cn = "购买", en_us = "Purchase"},
	[10094] = {zh_cn = "原地复活成功", en_us = "Revived On Spot"},
	[10095] = {zh_cn = "购买复活失败: %s", en_us = "Failed to Purchase Revival: %s"},
	[10096] = {zh_cn = "你需要原地复活吗？", en_us = "Do you want to revive on the spot?"},
	[10097] = {zh_cn = "消耗69 Robux原地复活", en_us = "Spend 69 Robux to revive on the spot"},
	[10098] = {zh_cn = "回主城复活", en_us = "Revive in Main City"},
	[10099] = {zh_cn = "创建船只", en_us = "Create Ship"},
	[10100] = {zh_cn = "没有船身", en_us = "No Ship Hull"},
	[10101] = {zh_cn = "打开宝箱", en_us = "Open Chest"},
	[10102] = {zh_cn = "宝箱", en_us = "Chest"},
	[10103] = {zh_cn = "即将沉没", en_us = "About to Sink"},
	[10104] = {zh_cn = "岛屿沉没剩余时间: %s", en_us = "Island sinking in: %s"},
	[10105] = {zh_cn = "运气太衰，没有抽中物品", en_us = "Unlucky! No item drawn."},
	[10106] = {zh_cn = "反馈", en_us = "Feedback"},
	[10107] = {zh_cn = "请在此输入你的反馈内容...", en_us = "Enter your feedback here..."},
	[10108] = {zh_cn = "反馈已提交", en_us = "Feedback submitted"},
	[10109] = {zh_cn = "感谢你的反馈！已同时提交到游戏分析和Roblox官方反馈系统", en_us = "Thanks for your feedback! It has been submitted to both game analytics and the Roblox feedback system."},
	[10110] = {zh_cn = "首次启航", en_us = "First Voyage"},
	[10111] = {zh_cn = "首次发现新岛屿并登陆", en_us = "Island Explorer"},
	[10112] = {zh_cn = "航行%s米", en_us = "Sail %s Meters"},
	[10113] = {zh_cn = "首次开启宝箱", en_us = "First Treasure"},
	[10114] = {zh_cn = "开启宝箱5个", en_us = "Treasure Hunter I"},
	[10115] = {zh_cn = "开启宝箱10个", en_us = "Treasure Hunter II"},
	[10116] = {zh_cn = "首次组建一艘完成的船", en_us = "Shipbuilder"},
	[10117] = {zh_cn = "拥有第二艘船", en_us = "Fleet Begins"},
	[10118] = {zh_cn = "徽章", en_us = "Badge"},
	[10119] = {zh_cn = "点击下方的徽章来查看详细信息", en_us = "Click the badges below to see more details"},
	[10120] = {zh_cn = "已获得", en_us = "Obtained"},
	[10121] = {zh_cn = "未获得", en_us = "Not obtained"},
	[10122] = {zh_cn = "选择一个徽章查看详情", en_us = "Select a badge to view details"},
	[10123] = {zh_cn = "初级小船 船身", en_us = "Primary Boat Hull"},
	[10124] = {zh_cn = "初级小船 旗帜", en_us = "Primary Boat Flag"},
	[10125] = {zh_cn = "初级小船 桅杆", en_us = "Primary Boat Mast"},
	[10126] = {zh_cn = "初级小船 绳子", en_us = "Primary Boat Rope"},
	[10127] = {zh_cn = "2级船 船身", en_us = "Tier 2 Ship Hull"},
	[10128] = {zh_cn = "2级船 前杆", en_us = "Tier 2 Bowsprit"},
	[10129] = {zh_cn = "2级船 桅杆", en_us = "Tier 2 Mast"},
	[10130] = {zh_cn = "2级船 舵", en_us = "Tier 2 Rudder"},
	[10131] = {zh_cn = "2级船 舵盘", en_us = "Tier 2 Wheel"},
	[10132] = {zh_cn = "2级船 锚", en_us = "Tier 2 Anchor"},
	[10133] = {zh_cn = "2级船 风帆1", en_us = "Tier 2 Sail 1"},
	[10134] = {zh_cn = "2级船 风帆2", en_us = "Tier 2 Sail 2"},
	[10135] = {zh_cn = "2级船 驾驶室", en_us = "Tier 2 Wheelhouse"},
	[10136] = {zh_cn = "2级船 前炮", en_us = "Tier 2 Front Cannon"},
	[10137] = {zh_cn = "2级船 右炮", en_us = "Tier 2 Right Cannon"},
	[10138] = {zh_cn = "2级船 左炮", en_us = "Tier 2 Left Cannon"},
	[10139] = {zh_cn = "奥林匹斯", en_us = "Olympus"},
}

local Players = game:GetService("Players")
local LocalizationService = game:GetService("LocalizationService")
local RunService = game:GetService("RunService")

local curCountryCode = 'zh_cn'

-- 只在客户端获取玩家地区信息
if RunService:IsClient() and Players.LocalPlayer then
    local success, countryCode = pcall(function()
        return LocalizationService:GetCountryRegionForPlayerAsync(Players.LocalPlayer)
    end)
    
    if success and countryCode then
        if countryCode == "CN" then
            curCountryCode = 'zh_cn'
        else
            curCountryCode = 'en_us'
        end
    end
end

function LanguageConfig.Get(key)
    return Text[key][curCountryCode]
end

return LanguageConfig